info = { version = "0.2.0", description = "Basic installer utility" }
bin = [
	{ target = "../../target/debug/charon", alias = "charon", perms = 0x755 },
]
data = [ 
	{ target = "index.charon", overwrite = false },
]
localdata = []
